image: microsoft/dotnet:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  tags:
    - docker

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: zengo
    POSTGRES_USER: zengo
    POSTGRES_PASSWORD: zengo
    DB_CONNECTION_STRING: "Server=postgres;Port=5432;Username=zengo;Password=zengo;Database=zengo;"
  script:
    - apt-get update \
      && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
      && rm -rf /var/lib/apt/lists/*
    - dotnet restore
    - dotnet test
  only:
    - master
  tags:
    - docker
