image: microsoft/dotnet:sdk
stages:
  - build
  - test
job1:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  only:
    - master
  tags:
    - docker
job2:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: zengo
    POSTGRES_USER: zengo
    POSTGRES_PASSWORD: ""
    DB_CONNECTION_STRING: "Server=postgres;Username=zengo;Database=zengo;"
  script:
    - dotnet restore
    - dotnet test ./Tests
  only:
    - master
  tags:
    - docker
