image: docker

services:
  - docker:dind

test:
  stage: test
  tags:
    - docker
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose build
    - docker-compose run test
