image: docker

services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose build

test:
  stage: test
  tags:
    - docker
  script:
    - docker-compose run test
