image: microsoft/dotnet:sdk
stages:
  - build
  - test
job1:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  only:
    - master
  tags:
    - docker
job2:
  stage: test
  script:
    - dotnet restore
    - dotnet test
  only:
    - master
  tags:
    - docker
