image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run test
