image: docker:stable

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose build

test:
  stage: test
  tags:
    - docker
  script:
    - docker-compose run test --rm
