image: microsoft/dotnet:sdk
stages:
  - build
  - test
job1:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  only:
    - master
  tags:
    - docker
job2:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
  script:
    - dotnet restore
    - dotnet test ./Tests
  only:
    - master
  tags:
    - docker
