trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: './Zengo.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
#  BACKEND: postgres
#  DB_CONNECTION_STRING: "Server=localhost;Username=postgres;Password=password;Database=zengo;"

#setup:
#  - script: |
#    choco install postgresql10 --force --params '/Password:password'
#    set PATH=%PATH%;C:\Program Files\PostgreSQL\10\bin;C:\Program Files\PostgreSQL\10\lib"
#    echo "##vso[task.setvariable variable=PATH;]%PATH%;C:\Program Files\PostgreSQL\10\bin;C:\Program Files\PostgreSQL\10\lib"

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'

- script: dotnet restore

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
